[package]
name = "problem-1-duplicate-const-generic"
version = "0.1.0"
authors = ["viruscamp <viruscamp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
